#!/bin/bash

# clone the repo with US-align
git clone https://github.com/pylelab/USalign.git
# Compile usalign
cd USalign
make

# Create alias for usalign ("~/.local/bin" is in the PATH)
mkdir -p ~/.local/bin
cd ~/.local/bin
mv ~/USalign usalign
ln -s ~/.local/bin/usalign/USalign USalign
